# 核心模块
# 这些模块从 main_pgvector.py 提取，用于组织代码结构

from .config import (
    JWT_SECRET,
    JWT_ALGORITHM,
    JWT_EXPIRATION_HOURS,
    OLLAMA_BASE_URL,
    OLLAMA_EMBEDDING_MODEL,
    OLLAMA_CHAT_MODEL,
    RERANK_MODEL,
    STORAGE_DIR,
    UPLOAD_DIR,
    DB_CONFIG,
    REDIS_CONFIG,
    VECTOR_STORE_TYPE,
    VECTOR_STORE_CONFIG,
    MILVUS_CONFIG,
    RATE_LIMIT,
    pool,
    redis_client,
    cache,
    rate_limiter,
    task_queue,
    workflow_engine,
    mcp_server,
    embedding_service,
    rerank_service,
    document_processor,
    monitoring_service,
    vector_store_instance,
)
from .database import (
    init_db,
    close_db,
    setup_database,
    create_default_user,
    create_default_system_config,
    get_db_connection,
)
# 审计日志装饰器（独立导入，避免循环依赖）
from .audit import audit_log, audit_log_with_changes

# 注意：utils 模块中的一些函数会在运行时动态导入
# 以避免循环导入问题
from .utils import (
    hash_password,
    verify_password,
    create_token,
    verify_token,
    get_current_user,
    get_current_user_optional,
    validate_pagination,
    call_ollama,
    add_embedding,
    vector_search,
    vector_search_multi,
    hybrid_search,
    full_text_search,
    semantic_search,
    unified_search,
    create_rate_limiter,
    rate_limit_chat,
    rate_limit_search,
    rate_limit_upload,
    validate_request_size,
    check_ip_whitelist,
)

__all__ = [
    # Config
    'JWT_SECRET',
    'JWT_ALGORITHM',
    'JWT_EXPIRATION_HOURS',
    'OLLAMA_BASE_URL',
    'OLLAMA_EMBEDDING_MODEL',
    'OLLAMA_CHAT_MODEL',
    'RERANK_MODEL',
    'STORAGE_DIR',
    'UPLOAD_DIR',
    'DB_CONFIG',
    'REDIS_CONFIG',
    'VECTOR_STORE_TYPE',
    'VECTOR_STORE_CONFIG',
    'MILVUS_CONFIG',
    'RATE_LIMIT',
    'pool',
    'redis_client',
    'cache',
    'rate_limiter',
    'task_queue',
    'workflow_engine',
    'mcp_server',
    'embedding_service',
    'rerank_service',
    'document_processor',
    'monitoring_service',
    'vector_store_instance',
    # Database
    'init_db',
    'close_db',
    'setup_database',
    'create_default_user',
    'create_default_system_config',
    'get_db_connection',
    # Utils
    'hash_password',
    'verify_password',
    'create_token',
    'verify_token',
    'get_current_user',
    'get_current_user_optional',
    'validate_pagination',
    'call_ollama',
    'add_embedding',
    'vector_search',
    'vector_search_multi',
    'hybrid_search',
    'full_text_search',
    'semantic_search',
    'unified_search',
    'create_rate_limiter',
    'rate_limit_chat',
    'rate_limit_search',
    'rate_limit_upload',
    'validate_request_size',
    'check_ip_whitelist',
]
